language: ruby
sudo: false

cache:
  bundler: true

matrix:
  fast_finish: true

  include:
    - rvm: 1.9.3
      env: RUN=default
    - rvm: 2.0.0
      env: RUN=default
    - rvm: 2.1.0
      env: RUN=default
    - rvm: 2.2.3
      env: RUN=default
    - rvm: 2.2.3
      # PHANTOMJS env variable is not used but it makes it easier to differentiate this build in Travis
      # https://github.com/travis-ci/travis-ci/issues/3225 - Easiest way to use 2.0 on Travis
      env: RUN=default PHANTOMJS=2.0
      before_script:
        - "mkdir phantom20"
        - "export PATH=`pwd`/phantom20:$PATH"
        - "echo $PATH"
        - "pushd ."
        - "cd phantom20"
        - "curl -L -O https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
        - "tar xjvf phantomjs-2.0.0-ubuntu-12.04.tar.bz2"
        - "popd"
    - rvm: 2.2.3
      env: RUN=default RUNNER=node
    - rvm: 2.2.3
      env: RUN=default
      gemfile: gemfiles/opal_master.gemfile

before_install:
  - git submodule update --init

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  irc: "irc.freenode.org#opal"

script:
  - "bundle exec rake $RUN"
